# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Korp with SB config

on:
  push:
    branches: 
      - "**"
  pull_request:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.3]

    steps:
    - name: Config repo
      uses: actions/checkout@v2
      with:
        repository: spraakbanken/korp-frontend-sb
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: ${{github.ref}}
        path: korp-frontend-sb
    - name: Main repo
      uses: actions/checkout@v2
      with:
        path: korp-frontend
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run tests
      run: |
        cd korp-frontend-sb
        yarn --frozen-lockfile
        cd ../korp-frontend
        yarn --frozen-lockfile
        echo '{"configDir": "../korp-frontend-sb/app"}' > run_config.json
        yarn actions-test
        echo "exited tests with code $?"
